# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lat', models.CharField(blank=True, default='', max_length=100)),
                ('lon', models.CharField(blank=True, default='', max_length=100)),
                ('addr', models.CharField(blank=True, default='', max_length=100)),
                ('amenity', models.CharField(blank=True, default='', max_length=100)),
                ('cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='latitude',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='longitude',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='name',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
